language: ruby
sudo: required

services:
  - postgresql

jdk:
    - oraclejdk8  # needed for local Neo4j 2.0+

install:
  - bundle install
  - bundle exec rake neo4j:install[community-3.1.0,test]
  - bundle exec rake neo4j:config[test,7474]
  - bundle exec rake neo4j:start[test]
  - bundle exec rake neo4j:disable_auth[test]
  - bundle exec rake neo4j:restart[test]
  - sleep 10s

before_script:
  - psql -c 'create database commute_calculator_test;' -U postgres
  - bundle exec rake neo4j:migrate:all
