language: ruby
sudo: required

services:
  - postgresql

jdk:
    - oraclejdk8  # needed for local Neo4j 2.0+

before_script:
  - psql -c 'create database commute_calculator_test;' -U postgres
  - noglob bundle exec rake neo4j:install[community-3.1.0, test]
  - noglob bundle exec rake neo4j:config[test,7474]
  - noglob bundle exec rake neo4j:disable_auth[test]
  - noglob bundle exec rake neo4j:start[test]
  - noglob bundle exec rake neo4j:migrate:all
