language: ruby

services:
  - postgresql
  - neo4j

before_install:
 - sudo apt-get install neo4j

before_script:
  - psql -c 'create database commute_calculator_test;' -U postgres
  - bundle exec rake neo4j:config[test,7474]
  - bundle exec rake neo4j:disable_auth[test]
  - bundle exec rake neo4j:start[test]
  - bundle exec rake neo4j:migrate:all



dist: trusty
sudo: required # service start commands use sudo by default
