default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: commute_calculator_development

test:
  <<: *default
  database: commute_calculator_test

production:
  <<: *default
  database: commute_calculator_production
  username: commute_calculator
  password: <%= ENV['COMMUTE_CALCULATOR_POSTGRES_PASSWORD'] %>
