# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d512cceb5786defdb5d4e06eb785e9d9506b56f4e9ab6358817e33f00b873f9ffe965ead1a01621e7ab20c49f093574b9234037a2958c2b68b74db4a51eceffa

test:
  secret_key_base: f72d11eb88ea26bae483d5e5a4e17bda2e361c53aa2e083c0de355d04839eb2136be6971c74075e8a450682b04d4c72705e04dee251fa0eeaf63bc6e5a56807b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
